# -*- python -*-
# Copyright 2016 Toyota Research Institute.  All rights reserved.
# This file marks a workspace root for the Bazel build system. see
# http://bazel.io/ .
workspace(name = "maliput")

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
    build_file = "tools/gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)

new_local_repository(
    name = "boost",
    path = "/usr",
    build_file = "tools/boost.BUILD",
)
